# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint5
    - joint4
    - joint3
    - joint2
    - joint1_2
    - joint1_1
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - joint5
      - joint4
      - joint3
      - joint2
arm_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint1_1
    - joint1_2
    - joint2
    - joint3
    - joint4
    - joint5

  gains:
    joint1_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
